#!/usr/bin/env python3
"""Static figure for 05강 4기 15강 — the gap between the definition of R^2 (ordered
pairs) and the mental picture (lecture §9/§10). The basis symbols e1=(1,0), e2=(0,1)
carry NO size and NO angle by themselves: choosing an inner product picks one of
infinitely many parallelograms. Euclidean (unit square) is just one choice; any
skewed / rescaled parallelogram is an equally valid non-Euclidean geometry.

Renders next to itself as an SVG embedded by the note.

Reproduce:  uv run --with matplotlib --with numpy python euclidean-vs-noneuclidean-04-season-15-09.py
"""
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, Polygon, Arc

OUT = Path(__file__).with_suffix(".svg")

# Three readings of the SAME pair of basis symbols e1=(1,0), e2=(0,1).
# Each panel draws where those symbols *land* in the plane under one choice of
# size/angle (i.e. one inner product). Stored as the images of e1, e2.
panels = [
    {
        "title": "Euclidean (square)",
        "subtitle": r"$\|e_1\|=\|e_2\|=1,\ \angle=90^\circ$",
        "e1": np.array([1.0, 0.0]),
        "e2": np.array([0.0, 1.0]),
        "note": "the standard / identity\ninner product",
    },
    {
        "title": "non-Euclidean (skew)",
        "subtitle": r"$\|e_1\|=\|e_2\|=1,\ \angle=45^\circ$",
        "e1": np.array([1.0, 0.0]),
        "e2": np.array([np.cos(np.radians(45)), np.sin(np.radians(45))]),
        "note": "same lengths,\nangle changed",
    },
    {
        "title": "non-Euclidean (rescaled)",
        "subtitle": r"$\|e_1\|=2,\ \|e_2\|=1.5,\ \angle=60^\circ$",
        "e1": np.array([2.0, 0.0]),
        "e2": np.array([1.5 * np.cos(np.radians(60)), 1.5 * np.sin(np.radians(60))]),
        "note": "lengths and\nangle changed",
    },
]

C1, C2 = "#1f6feb", "#d1242f"   # e1, e2 colours
FILL = "#1f6feb"

fig, axes = plt.subplots(1, 3, figsize=(11.4, 4.1))

for ax, p in zip(axes, panels):
    e1, e2 = p["e1"], p["e2"]
    # parallelogram O, e1, e1+e2, e2
    quad = np.array([[0, 0], e1, e1 + e2, e2])
    ax.add_patch(Polygon(quad, closed=True, facecolor=FILL, alpha=0.13,
                         edgecolor="none", zorder=1))
    # the two "axes" generated by scalar multiples of e1 and e2
    for vec, col in ((e1, C1), (e2, C2)):
        t = np.linspace(-0.25, 1.45, 2)
        ax.plot(t * vec[0], t * vec[1], color=col, lw=0.9, ls=(0, (6, 4)),
                alpha=0.5, zorder=1)
    # right-angle marker only in the Euclidean panel (90 degrees)
    ang = np.degrees(np.arctan2(*e2[::-1])) - np.degrees(np.arctan2(*e1[::-1]))
    if abs(ang - 90) < 1e-6:
        s = 0.16
        u1, u2 = e1 / np.linalg.norm(e1), e2 / np.linalg.norm(e2)
        sq = np.array([s * u1, s * u1 + s * u2, s * u2])
        ax.plot(sq[:, 0], sq[:, 1], color="#57606a", lw=1.0, zorder=4)
    else:
        ax.add_patch(Arc((0, 0), 0.7, 0.7, angle=0,
                         theta1=np.degrees(np.arctan2(*e1[::-1])),
                         theta2=np.degrees(np.arctan2(*e2[::-1])),
                         color="#57606a", lw=1.2, zorder=4))
    # the basis vectors as arrows
    for vec, col, lab in ((e1, C1, r"$e_1=(1,0)$"), (e2, C2, r"$e_2=(0,1)$")):
        ax.add_patch(FancyArrowPatch((0, 0), vec, arrowstyle="-|>",
                                     mutation_scale=15, lw=2.3, color=col,
                                     shrinkA=0, shrinkB=0, zorder=5))
        off = 0.10
        ax.text(vec[0] + off, vec[1] + off, lab, color=col, fontsize=10.5,
                weight="bold", zorder=6)
    ax.scatter([0], [0], s=14, color="#24292f", zorder=6)
    ax.text(0.06, 1.0, p["note"], transform=ax.transAxes, fontsize=9,
            color="#57606a", va="top", ha="left")
    ax.set_title(p["title"] + "\n" + p["subtitle"], fontsize=11)
    ax.set_xlim(-0.8, 3.4)
    ax.set_ylim(-0.6, 2.4)
    ax.set_aspect("equal")
    ax.axhline(0, color="#e3e8ee", lw=0.8, zorder=0)
    ax.axvline(0, color="#e3e8ee", lw=0.8, zorder=0)
    ax.set_xticks([]); ax.set_yticks([])
    for sp in ax.spines.values():
        sp.set_visible(False)

fig.suptitle(
    r"Same ordered pairs $e_1=(1,0),\ e_2=(0,1)$ — size & angle are NOT in the definition of $\mathbb{R}^2$",
    fontsize=12.5, y=1.02)
fig.tight_layout()
fig.savefig(OUT, format="svg", bbox_inches="tight")
print(f"wrote {OUT}")
for p in panels:
    e1, e2 = p["e1"], p["e2"]
    ang = np.degrees(np.arccos(
        (e1 @ e2) / (np.linalg.norm(e1) * np.linalg.norm(e2))))
    print(f"  {p['title']:26s} |e1|={np.linalg.norm(e1):.2f} "
          f"|e2|={np.linalg.norm(e2):.2f} angle={ang:.1f} deg")
